version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  backend:
    build: ./app
    volumes:
      - ./app:/var/www/app
    ports:
      - "3000:3000"
    depends_on:
      - db